* CSC-271 project 1: linux mint web server
For this project I will be installing an Apache webserver onto a linux mint installation.

* Update current linux mint packages
#+BEGIN_SRC bash
apt update && apt upgrade
#+END_SRC

* Install packages I need
The apache2 package will allow us to get a simple webserver going. apache2-utils will be used to get an https server going and finally any text editor.
#+BEGIN_SRC bash
apt install apache2 emacs
#+END_SRC

* Remove the CUPS server
No need to have a printing service on a webserver.
#+BEGIN_SRC bash
systemctl stop cups

systemctl disable cups
#+END_SRC

* Build That Wall
#+BEGIN_SRC bash
  iptables -P INPUT DROP 		# Make default policy of INPUT chain to DROP

  iptables -A INPUT \ 		# Append the following to INPUT chain
	   -i enp1s0 \		# on the network interface enp1s0
	   -p tcp \ 		# with TCP connections
	   --dport 80 \		# on port 80
	   -j ACCEPT		# accept the connection.
#+END_SRC


* Add Groups
#+BEGIN_SRC bash
groupadd editors
#+END_SRC
For the assignment, we only need one group. This group's members will be able to edit the content served by apache. Users with more privledge will have be added to the sudo group and those with less privledge won't have either, only allowing them to edit their home directories if they have ones.

* Add Users
The first user I'll add is the web developer. This trusted account will be able to do anything and everything to the Linux Server. This account will also be given a generic password for them to change.
#+BEGIN_SRC bash
useradd --comment "Web Developer" \
  --create-home \
  --shell /bin/bash \
  --groups sudo,editors \
  webdev1

  passwd webdev1
#+END_SRC
Next, the content editor will be added. The content editor will be able to write web page content and add pictures by editing the html.

#+BEGIN_SRC bash
  useradd --comment "Content Editor" \
  --create-home \
  --shell /bin/bash \
  --groups editors \
  ceditor

  passwd ceditor
#+END_SRC

Finally, the test user will be able to logon and walk around the server with read only access.
#+BEGIN_SRC bash
  useradd --comment "Test User" \
  --shell /bin/bash \
  --no-create-home  testusr

  passwd testusr
#+END_SRC

* Content folder permissions
Adding the content pages to groups will allow us to control who can edit them.
#+BEGIN_SRC bash
  chgrp --recursive editors /var/www
#+END_SRC
I will then make it where only people in the same group as the file will be able to edit the files.
#+BEGIN_SRC bash
  chgrp chmod --recursive 775 /var/www
#+END_SRC



* Adding a Backup System
For this assigment, I have two seperate partitions that I care about. The first is /var/html and the second is the root partition. So I will make a script that backs them up.

** BUT FIRST!
The backup that I am doing requrires an ssh connection. So to handle authentication I will use a key pair.
#+BEGIN_SRC bash
  su
#+END_SRC
It is important that I make the key as root so systemd can use the keys.
#+BEGIN_SRC bash
  ssh-keygen
#+END_SRC
Is the command that creates a public and private key for ssh authentication. The private key stays on the client machine and the public key is appended to the ~/.ssh/authorized_keys file in the user that will be getting logged into on the server.

** Script Time
The following is the script for backing up the webserver content.
/opt/backup:
#+BEGIN_SRC bash
#!/usr/bin/env bash

cd /
WEB_CONTENT="./var/www/html"
BACKUP_SERVER="seth@10.90.31.127" # current IP of backup server as of demo
# Full path of new backup file
BACKUP_DEST="/home/seth/backups/`date +"content-backup-%Y-%m-%d.tar.gz"`"

# This zips the file and sends it to the backup server without
# making a local copy.
tar --preserve-permissions \
    --gzip --create --file=- \
    $WEB_CONTENT | ssh $BACKUP_SERVER "cat > $BACKUP_DEST"

BACKUP_DEST="/home/seth/backups/`date +"server-backup-%Y-%m-%d.tar.gz"`"

tar --preserve-permissions \
    --gzip --create \
    --exclude=$WEB_CONTENT \
    --exclude=/proc \
    --exclude=/dev \
    --exclude=/mnt \
    --exclude=/run \
    --file=- / \
    | ssh $BACKUP_SERVER "cat > $BACKUP_DEST"

#+END_SRC

** Systemd Timer Time

Here is the systemd service that runs the backup script
/etc/systemd/system/backup.service:
#+BEGIN_SRC
[Unit]
Description=System backup script

[Service]
Type=oneshot
ExecStart=/opt/backup

#+END_SRC

This would be usless without a systemd timer to run the service file.
/etc/systemd/system/backup.timer:
#+BEGIN_SRC
[Unit]
Description=System backup script timer

[Timer]
OnCalendar=weekly
Persistent=true

[Install]
WantedBy=timers.target
#+END_SRC
We don't need this script to be run on startup. Only once a week. Therefore I will only start the service, not enable it.

#+BEGIN_SRC bash
systemctl daemon-reload
systemctl start backup
#+END_SRC
